### ISSUE TITLE
Does not build on FreeBSD

### ISSUE THREAD

**Issue by jTd7bPLFb** [Beldex-Coin/beldex#160]
**Describe the bug**
Does not compile on FreeBSD 14.1 nor 15.0

/sandbox/beldex/src/cryptonote_config.h:239:45: error: constexpr variable 'NETWORK_ID' must be initialized by a constant expression

**To Reproduce**
Follow the instructions you have in the git, to build on FreeBSD.

**Expected behaviour**
Would be nice to compile.
Only app holding my migration for FreeBSD.
The Linux version does not run in linux jails either.

**Current Behaviour**

first of the errors
/sandbox/beldex/src/cryptonote_config.h:239:45: error: constexpr variable 'NETWORK_ID' must be initialized by a constant expression

**Screenshots or Logs**
/sandbox/beldex/src/cryptonote_config.h:239:45: error: constexpr variable 'NETWORK_ID' must be initialized by a constant expression

**Additional Information (please complete the following information):**
 FreeBSD 14.1
beldexd from your git
